// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVAB24M_ezA1H_Prknb1oDZN1c7OF-VI4',
    appId: '1:226042461945:web:3ee8643fe4f5ac6a146c28',
    messagingSenderId: '226042461945',
    projectId: 'ashwa-b3e20',
    authDomain: 'ashwa-b3e20.firebaseapp.com',
    storageBucket: 'ashwa-b3e20.firebasestorage.app',
    measurementId: 'G-1W8FS1YLNM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMJHMaTs5eBCOiXVfDTA8b3olv2bPEgfQ',
    appId: '1:226042461945:android:e74c7164c1b0826a146c28',
    messagingSenderId: '226042461945',
    projectId: 'ashwa-b3e20',
    storageBucket: 'ashwa-b3e20.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6-UZVbPNG6f03TOX97ZzIzfnYjPg1OEU',
    appId: '1:226042461945:ios:72acc7b7c498cc43146c28',
    messagingSenderId: '226042461945',
    projectId: 'ashwa-b3e20',
    storageBucket: 'ashwa-b3e20.firebasestorage.app',
    iosBundleId: 'com.example.adminControl',
  );
}
